// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChwpPnk3X8jXoWM_wMeTnSbi9bxzaGNgg',
    appId: '1:500767059951:web:60e081c07ca12fdc33901a',
    messagingSenderId: '500767059951',
    projectId: 'flutter-carpool-app-f58f4',
    authDomain: 'flutter-carpool-app-f58f4.firebaseapp.com',
    storageBucket: 'flutter-carpool-app-f58f4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKcUJUewcODAi3sIhh3NTfD73dDYFiQYk',
    appId: '1:500767059951:android:5f51ab5a406c2b5233901a',
    messagingSenderId: '500767059951',
    projectId: 'flutter-carpool-app-f58f4',
    storageBucket: 'flutter-carpool-app-f58f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5FTlm46u9ogWsf3MBvLCdVqVV0ko3tPc',
    appId: '1:500767059951:ios:00ead8bce14d45b833901a',
    messagingSenderId: '500767059951',
    projectId: 'flutter-carpool-app-f58f4',
    storageBucket: 'flutter-carpool-app-f58f4.appspot.com',
    iosBundleId: 'com.ride.sharing.rideSharingPlatform',
  );
}
